project:
  type: website
  output-dir: docs

execute:
  freeze: auto
  
website:
  page-navigation: true
  site-url: https://jmhumphreys.github.io/flusion/
  repo-actions: [edit, issue]
  open-graph: true
  sidebar:
    style: "floating"
    logo: images/flusion.png
    align: center
    search: true
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/JMHumphreys/flusion
          - text: Report a Bug
            url:  https://github.com/JMHumphreys/flusion/issues
    contents:
      - section: "Overview"
        contents:
          - index.qmd
      - section: "Explore the Data"
        contents:
          - explore.qmd
      - text: "---"
      - section: "Model Construction"
        contents:
          - construction/preprocessing/preprocessing.qmd
          - construction/organize/organize.qmd
          - construction/model/model.qmd
          - construction/results/results.qmd
  page-footer:
    border: false
    left: "Published with [Quarto](https://quarto.org/) v1.2.335"
    right: "© 2023 [John Humphreys](/about) | [MIT License](/license)"
        
format:
  html:
    theme:
      light: flatly
      dark: darkly
    revealjs:
      #logo: images/logo-bg.png
      css: scss/styles.css
    link-external-icon: true
    link-external-newwindow: true
    smooth-scroll: true
    highlight-style: gruvbox
    df-print: kable
    
editor: visual