project:
  type: website
  output-dir: docs

execute:
  freeze: auto
  
website:
  page-navigation: true
  title: "f(l)usion"
  site-url: https://jmhumphreys.github.io/flusion_model/
  open-graph: true
  #favicon: images/biogeo.png
  navbar:
    #logo: images/logo-bg.png
    title: "f(l)usion"
    right:
      - href: index.qmd
        text: Home
      - href: cons_index.qmd
        text: Construction
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/JMHumphreys/flusion_model
          - text: Report a Bug
            url:  https://github.com/JMHumphreys/flusion_model/issues
  page-footer:
    border: false
    left: "Published with [Quarto](https://quarto.org/) v1.2.335"
    right: "© 2023 [John Humphreys](/about) | [MIT License](/license)"
        
format:
  html:
    theme:
      light: flatly
      dark: darkly
    revealjs:
      #logo: images/logo-bg.png
      css: scss/styles.css
    link-external-icon: true
    link-external-newwindow: true
    smooth-scroll: true
    highlight-style: gruvbox
    df-print: kable
    
editor: visual